import type { RiskLevel } from "@prisma/client";

export type NormalizedLicenseSnapshot = {
  clientId: string;
  instanceId: string;
  collectedAt: Date;
  weekReference: string;
  overviewSysId: string;
  subscriptionSysId: string;
  entitlementSysId: string;
  licenseSysId: string;
  productCode: string;
  licenseName: string | null;
  entitlementName: string | null;
  meterType: string | null;
  unitOfMeter: string | null;
  entitlementId: string | null;
  parentEntitlementId: string | null;
  purchasedCount: number | null;
  allocatedCount: number | null;
  availableCount: number | null;
  usagePercent: number | null;
  overviewStatus: string | null;
  overviewSubscriptionType: string | null;
  licenseCount: number | null;
  licenseAllocated: number | null;
  licenseAvailable: number | null;
  licenseUsagePercent: number | null;
  allocatedStatus: string | null;
  licenseType: string | null;
  licenseCategory: string | null;
  licenseWeight: number | null;
  tableCount: number | null;
  tablesUsed: number | null;
  startDate: Date | null;
  endDate: Date | null;
  daysToExpire: number | null;
  expired: boolean;
  displayOnly: boolean;
  isCapped: boolean;
  autoSync: boolean;
  riskLevel: RiskLevel;
  riskReason: string;
  rawOverview: unknown;
  rawEntitlement: unknown | null;
  rawLicenseDetails: unknown | null;
};

export type LicenseWeeklyComparison = {
  currentUsagePercent: number | null;
  previousUsagePercent: number | null;
  usageDelta: number | null;
  currentAllocated: number | null;
  previousAllocated: number | null;
  allocatedDelta: number | null;
  currentPurchased: number | null;
  previousPurchased: number | null;
  purchasedDelta: number | null;
  currentRisk: RiskLevel | null;
  previousRisk: RiskLevel | null;
  riskChanged: boolean;
};
